development:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  database: <%= ENV["DATABASE_NAME"] || 'bird_view_development' %>
  pool: 5
  username: <%= ENV["DATABASE_USR"] %>
  password: <%= ENV["DATABASE_PWD"] %>

test:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  database: <%= ENV['DATABASE_NAME'] || 'bird_view_test' %>
  pool: 5
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  username: <%= ENV["DATABASE_USR"] %>
  password: <%= ENV["DATABASE_PWD"] %>

staging:
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  url: <%= ENV["DB_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] || 15 %>

production:
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] || 15 %>
